application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # multi_port: [9000, 9001, 9002]    # Experimental: Multiple port support

logging:
  level: INFO
  format: json
  output: /var/log/app.log
  # ai_analysis: enabled               # Experimental: AI-based log analysis

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  # distributed: true                  # Experimental: Distributed DB support

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # chaos_engineering: enabled         # Experimental: Chaos testing mode

# --- Experimental features --- 
# These are not enabled for production, only use in controlled test environments.
# ai_features:
#   predictive_scaling: true
#   anomaly_detection: true
#   auto_optimization: true
#   model_version: "v2.1.0"
#
# cloud_providers:
#   - aws
#   - azure
#   - gcp
#   - digitalocean
#
# security:
#   zero_trust: enabled
#   encryption: AES-256
#   audit_logging: comprehensive
